### ISSUE TITLE
Containerlab will not deploy

### ISSUE THREAD

**Issue by tknipper11** [PacketAnglers/containerlab#1]
Having an issue deploying containerlab.  It appears the deploy never finishes and hangs here:

sysadmin@server:~/labs$ sudo clab deploy -t containerlab/topologies/L2LS/L2LS.yaml --reconfigure
[sudo] password for sysadmin: 
INFO[0000] Containerlab v0.31.0 started                 
INFO[0000] Parsing & checking topology file: L2LS.yaml  
INFO[0000] Removing /home/sysadmin/labs/clab-L2LS directory... 
INFO[0000] Creating lab directory: /home/sysadmin/labs/clab-L2LS 
INFO[0000] Creating docker network: Name="mgmt", IPv4Subnet="172.100.100.0/24", IPv6Subnet="", MTU="1500" 
INFO[0000] Creating container: "HOSTB"                  
INFO[0000] Creating container: "HOSTA"                  
INFO[0000] Creating container: "graphite"               
INFO[0000] Creating container: "LEAF3"                  
INFO[0000] Creating container: "LEAF2"                  
INFO[0000] Creating container: "SPINE1"                 
INFO[0000] Creating container: "LEAF1"                  
INFO[0000] Creating container: "SPINE2"                 
INFO[0000] Creating container: "LEAF4"                  
INFO[0000] Creating virtual wire: LEAF1:et4 <--> LEAF2:et4 
INFO[0000] Creating virtual wire: LEAF1:et3 <--> LEAF2:et3 
INFO[0001] Creating virtual wire: HOSTB:eth1 <--> LEAF3:et5 
INFO[0001] Creating virtual wire: HOSTA:eth1 <--> LEAF1:et5 
INFO[0001] Creating virtual wire: HOSTA:eth2 <--> LEAF2:et5 
INFO[0001] Creating virtual wire: HOSTB:eth2 <--> LEAF4:et5 
INFO[0001] Creating virtual wire: LEAF3:et4 <--> LEAF4:et4 
INFO[0001] Creating virtual wire: LEAF3:et3 <--> LEAF4:et3 
INFO[0001] Creating virtual wire: SPINE1:et4 <--> LEAF4:et1 
INFO[0001] Creating virtual wire: SPINE1:et2 <--> LEAF2:et1 
INFO[0001] Creating virtual wire: SPINE1:et3 <--> LEAF3:et1 
INFO[0001] Creating virtual wire: SPINE1:et1 <--> LEAF1:et1 
INFO[0001] Creating virtual wire: SPINE2:et3 <--> LEAF3:et2 
INFO[0001] Creating virtual wire: SPINE2:et4 <--> LEAF4:et2 
INFO[0001] Creating virtual wire: SPINE1:et6 <--> SPINE2:et6 
INFO[0001] Creating virtual wire: SPINE2:et2 <--> LEAF2:et2 
INFO[0001] Creating virtual wire: SPINE1:et5 <--> SPINE2:et5 
INFO[0001] Creating virtual wire: SPINE2:et1 <--> LEAF1:et2 
INFO[0003] Running postdeploy actions for Arista cEOS 'SPINE1' node 
INFO[0003] Running postdeploy actions for Arista cEOS 'LEAF1' node 
INFO[0003] Running postdeploy actions for Arista cEOS 'LEAF3' node 
INFO[0003] Running postdeploy actions for Arista cEOS 'SPINE2' node 
INFO[0003] Running postdeploy actions for Arista cEOS 'LEAF2' node 
INFO[0003] Running postdeploy actions for Arista cEOS 'LEAF4' node 

I have tried running on ubuntu, Centos, AWS Ubuntu and all have the same result.  on a console of Ubuntu I see the following message 6 times when the 6 postdeploy actions kick off:

cgroup2: Unknown parameter  'mode'

Here is the version information:

CONTAINERLAB:
sysadmin@server:~/labs$ clab version

                           _                   _       _     
                 _        (_)                 | |     | |    
 ____ ___  ____ | |_  ____ _ ____   ____  ____| | ____| | _  
/ ___) _ \|  _ \|  _)/ _  | |  _ \ / _  )/ ___) |/ _  | || \ 
( (__| |_|| | | | |_( ( | | | | | ( (/ /| |   | ( ( | | |_) )
\____)___/|_| |_|\___)_||_|_|_| |_|\____)_|   |_|\_||_|____/ 

    version: 0.31.0
     commit: 43ab9b15
       date: 2022-08-11T20:27:29Z
     source: https://github.com/srl-labs/containerlab
 rel. notes: https://containerlab.dev/rn/0.31/

UBUNTU:
sysadmin@server:~/labs$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

DOCKER:
sysadmin@server:~/labs$ docker version
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.7
  GitCommit:        0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc:
  Version:          1.1.3
  GitCommit:        v1.1.3-0-g6724737
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by kolson22** [comment]
If you do a "docker logs -f SPINE2" and see this while it's hanging

```Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted```

I was able to resolve by doing this as root

``` bash 
echo 'GRUB_CMDLINE_LINUX=systemd.unified_cgroup_hierarchy=false' > /etc/default/grub.d/cgroup.cfg
update-grub
reboot
```

**Comment by mthiel117** [comment]
Using Ubuntu 20.04 this issue doe exist.
